### ISSUE TITLE
Documentation upload fails if tab not selected first

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk#1390]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When attempting to upload swagger documentation to a catalogue, if you do not select a tab before pasting the swagger doc the documentation will not work.

**What is the expected behavior?**
Pasting a swagger doc into the textbox without having to first select the tab will result in the document importing ok.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

When viewing a catalogue in the Dashboard:

- Click `Attach documentation`
- Paste valid swagger document into textbox
- Click `Attach documentation`
- Click `Update`
- Visit portal and check the documentation - this will result in `API documentation format is not supported` being displayed.

If you follow the same steps except for clicking `From swagger file` before pasting the document into the textbox, the documentation will work ok.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Current at time of logging (1.4.2)

**Comment by ilijabojanovic** [comment]
Verified

**Comment by LinuxUser3** [comment]
Still not working. 

If you try this: 
```
{
  "swagger" : "2.0",
  "info" : {
    "title" : "hello",
    "version" : "1.0.0",
    "description" : "to request some information"
  },
  "schemes" : [ "https" ],
  "paths" : {
    "/" : {
      "get" : {
        "produces" : [ "application/json" ],
        "responses" : {
          "200" : {
            "description" : "successful operation"
          }
        }
      }
    }
  },
  "host" : "this.com",
  "basePath" : "/path"
}
```

Regardless, if you click at "From swagger file" or not - **Tyk Cloud** still shows error message in Portal Management: 
![screenshot 2018-01-15 10-13-10](https://user-images.githubusercontent.com/31533791/34935124-170f0834-f9dd-11e7-8cbb-5373d833764d.png)

**Comment by ConsM** [comment]
@LinuxUser3 this fix will be part of 2.5 release

**Comment by LinuxUser3** [comment]
> this fix will be part of 2.5 release

Oh, that's good to hear. Thanks!
Do you know when v2.5 will be released?

**Comment by LuanvP** [comment]
@LinuxUser3 we're aiming for the week of the 22nd :)

**Comment by LinuxUser3** [comment]
Perfect! Looking forward.

**Comment by LinuxUser3** [comment]
Hi! - Any update on this?

**Comment by buger** [comment]
2.5 was released few days ago, try it out, should be fixed 👌

**Comment by LinuxUser3** [comment]
Sadly, no. I've also deleted documentation file and uploaded it. Error still exists.

**Comment by buger** [comment]
Also try cleaning up browser cache first. 

I will re-open the issue in meanwhile.

**Comment by LinuxUser3** [comment]
Cleaning browser cash had no effect. My steps:
a) deleted documentation
b) Closed browser 
c) Browser started, new login, uploaded documentation.
d) verified in Portal Management: error still exists.

**Comment by davegarvey** [comment]
I've found that behaviour changes between page reloads.

Using this URL https://tyk.cloud.tyk.io/portal/apis/5a6fd654ded3fc000134e0b9/documentation/, I had the following results:

- doc loads, validator valid
- doc loads, validator error
- doc doesn’t load, ‘failed to load spec’ message (request for `raw` URL gives 404)
- 404, ‘api catalogue not found’

**Comment by lghiur** [comment]
@davegarvey you are right, I can see the same behaviors on page reload. Will keep investigating.

**Comment by lghiur** [comment]
@LinuxUser3 I have tried the steps u described and apparently it works for my example. As I mentioned above we will keep investigating though. 

My example:
https://tykqa.cloud.tyk.io/portal/apis/5a6ffeeaded3fc000134e0c8/documentation/

**Comment by LinuxUser3** [comment]
I have just immediately found out by chance that this issue has something to do with settings:
**Protect API Catalogue** --> **API Catalogue is login-only** 
If you deselect checkbox, error will disappear !  
If you select it again, error will appear again.

**Comment by ilijabojanovic** [comment]
@LinuxUser3 

Error for validation is expected.
If you enable API Catalogue is login-only for Swagger validator will always show error, because json validation doesn't work for protected Api Catalogue.

**Comment by LinuxUser3** [comment]
I understand, but this issue is completely irritating for all participants: the creator (like me) wants to provide a valid Swagger Doc and the consumer is irritated because he suspects a non-well formatted documentation. 

There should exists a workaround, a hint or something else.

**Comment by LuanvP** [comment]
@LinuxUser3 
I've opened a ticket for this internally and we'll get back to you once we've found a solution.

**Comment by LuanvP** [comment]
separate public ticket opened for users to track, including a potential workaround: https://github.com/TykTechnologies/tyk/issues/1619
