### ISSUE TITLE
[Dashboard] ngRepeat:dupes issues

### ISSUE THREAD

**Issue by nililee** [TykTechnologies/tyk#1488]
**Do you want to request a *feature* or report a *bug*?**
**BUG**

**What is the current behavior?**
**When I enter ENDPOINT DESIGNER tab in API Designer - Edit API, the entries I registered are not appeared intermittently. Console errors showed as follows:**

app.5d3412e608d096c6bd82.js:1 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: item in $ctrl.list track by item.id, Duplicate key: 3288, Duplicate value: {"id":3288,"method":{"id":"post"},"path":"/v1/csco/cscoIdDupCheck","plugins":[{"id":"trackEndpoint","hasDetails":false,"name":"Track endpoint"}],"pluginsData":{"trackEndpoint":true,"cache":false,"circuitBreaker":{"triggerThresholdPercentage":10,"sampleSize":100,"returnToServiceIn":60},"whitelist":false,"bodyTransform":{"request":{"inputType":{"id":"json"},"enableSession":false,"input":"","templateRaw":"","output":""},"response":{"inputType":{"id":"json"},"input":"","templateRaw":"","output":""}},"requestSizeLimit":{"sizeLimit":100},"methodTransform":{"toMethod":{"id":"get","name":"GET"}},"mockResponse":{"code":200,"responseBody":"","headers":{}},"virtualPath":{"jsFunctionToCall":"myVirtualHandler","codeEditor":""},"ignore":false,"doNotTrackEndpoint":false,"modifiedHeaders":{"response":{"added":{},"deleted":[]},"request":{"added":{},"deleted":[]}},"blacklist":false,"urlRewrite":{"matchPattern":"","rewriteTo":"","triggers":[]},"enforcedTimeout":{"value":60}},"collapsed":true}
http://errors.angularjs.org/1.6.8/ngRepeat/dupes?p0=item%20in%20%24ctrl.list%20track%20by%20item.id&p1=3288&p2=%7B%22id%22%3A3288%2C%22method%22%3A%7B%22id%22%3A%22post%22%7D%2C%22path%22%3A%22%2Fv1%2Fcsco%2FcscoIdDupCheck%22%2C%22plugins%22%3A%5B%7B%22id%22%3A%22trackEndpoint%22%2C%22hasDetails%22%3Afalse%2C%22name%22%3A%22Track%20endpoint%22%7D%5D%2C%22pluginsData%22%3A%7B%22trackEndpoint%22%3Atrue%2C%22cache%22%3Afalse%2C%22circuitBreaker%22%3A%7B%22triggerThresholdPercentage%22%3A10%2C%22sampleSize%22%3A100%2C%22returnToServiceIn%22%3A60%7D%2C%22whitelist%22%3Afalse%2C%22bodyTransform%22%3A%7B%22request%22%3A%7B%22inputType%22%3A%7B%22id%22%3A%22json%22%7D%2C%22enableSession%22%3Afalse%2C%22input%22%3A%22%22%2C%22templateRaw%22%3A%22%22%2C%22output%22%3A%22%22%7D%2C%22response%22%3A%7B%22inputType%22%3A%7B%22id%22%3A%22json%22%7D%2C%22input%22%3A%22%22%2C%22templateRaw%22%3A%22%22%2C%22output%22%3A%22%22%7D%7D%2C%22requestSizeLimit%22%3A%7B%22sizeLimit%22%3A100%7D%2C%22methodTransform%22%3A%7B%22toMethod%22%3A%7B%22id%22%3A%22get%22%2C%22name%22%3A%22GET%22%7D%7D%2C%22mockResponse%22%3A%7B%22code%22%3A200%2C%22responseBody%22%3A%22%22%2C%22headers%22%3A%7B%7D%7D%2C%22virtualPath%22%3A%7B%22jsFunctionToCall%22%3A%22myVirtualHandler%22%2C%22codeEditor%22%3A%22%22%7D%2C%22ignore%22%3Afalse%2C%22doNotTrackEndpoint%22%3Afalse%2C%22modifiedHeaders%22%3A%7B%22response%22%3A%7B%22added%22%3A%7B%7D%2C%22deleted%22%3A%5B%5D%7D%2C%22request%22%3A%7B%22added%22%3A%7B%7D%2C%22deleted%22%3A%5B%5D%7D%7D%2C%22blacklist%22%3Afalse%2C%22urlRewrite%22%3A%7B%22matchPattern%22%3A%22%22%2C%22rewriteTo%22%3A%22%22%2C%22triggers%22%3A%5B%5D%7D%2C%22enforcedTimeout%22%3A%7B%22value%22%3A60%7D%7D%2C%22collapsed%22%3Atrue%7D
    at vendors.5d3412e608d096c6bd82.js:424
    at vendors.5d3412e608d096c6bd82.js:424
    at $watchCollectionAction (vendors.5d3412e608d096c6bd82.js:424)
    at Scope.$digest (vendors.5d3412e608d096c6bd82.js:424)
    at ChildScope.$apply (vendors.5d3412e608d096c6bd82.js:424)
    at HTMLButtonElement.<anonymous> (vendors.5d3412e608d096c6bd82.js:424)
    at HTMLButtonElement.dispatch (vendors.5d3412e608d096c6bd82.js:29)
    at HTMLButtonElement.elemData.handle (vendors.5d3412e608d096c6bd82.js:29)
(anonymous) @ app.5d3412e608d096c6bd82.js:1
$digest @ vendors.5d3412e608d096c6bd82.js:424
$apply @ vendors.5d3412e608d096c6bd82.js:424
(anonymous) @ vendors.5d3412e608d096c6bd82.js:424
dispatch @ vendors.5d3412e608d096c6bd82.js:29
elemData.handle @ vendors.5d3412e608d096c6bd82.js:29

**What is the expected behavior?**
**The entries I registered appears.**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Dashboard v1.5.1

**Comment by lghiur** [comment]
@nililee Thank you for raising this issues, we'll take a look into it. 
Also, can u share with us your api definition? that would help us debug the problem.

**Comment by nililee** [comment]
Sure, you can connect our dashboard site at http://13.125.4.63:3000 by the account of test20798@test.com/test123.

**Comment by ilijabojanovic** [comment]
Fixed and verified

**Comment by nililee** [comment]
I don't understand what you mean by "Fixed and verified". Error still raised: http://13.125.4.63:3000/#/apis/designer/5a8d1f7552274300011f6a7b.

**Comment by lonelycode** [comment]
It means that a PR has been submitted, tested and merged and is ready to go into the next release.
