### ISSUE TITLE
Modify Header and URL Rewrite are now incompatible with each other

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk#1524]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
Seems like CORS and url rewrite are incompatible with each other. 

**What is the expected behavior?**
To both work. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I have created a small test 
1  - api with modify header on the response (add and delete) - works well
2 - **Added** url rewrite (now have 2 plugins) - just rewrite is working and I cannot see the header I have added (and can see the header I have deleted)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Was tested on cloud version 1.5.2

**Comment by ilijabojanovic** [comment]
@letzya @buger @excieve 

I can reproduce this issue on all stable versions from 2.4.0 to current version. I didn't tried this on 2.3.X versions. 

Here is testing definition 

```
{
    "id": "5a9ebd1555c18f000183f004",
    "name": "ilija9",
    "slug": "ilija9",
    "api_id": "bc9cf71f3a234f116acfdf05f1ce6c5c",
    "org_id": "5935d76307f81b0001c7c1a0",
    "use_keyless": true,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "",
        "use_certificate": false
    },
    "use_basic_auth": false,
    "use_mutual_tls_auth": false,
    "client_certificates": [],
    "upstream_certificates": {},
    "enable_jwt": false,
    "use_standard_auth": false,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "default_version": "",
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {
                    "transform_headers": [
                        {
                            "delete_headers": [
                                "User-Agent"
                            ],
                            "add_headers": {
                                "add": "request"
                            },
                            "path": "/ip",
                            "method": "GET",
                            "act_on": false
                        }
                    ],
                    "transform_response_headers": [
                        {
                            "delete_headers": [
                                "X-Powered-By"
                            ],
                            "add_headers": {
                                "add": "response"
                            },
                            "path": "/ip",
                            "method": "GET",
                            "act_on": false
                        }
                    ],
                    "url_rewrites": [
                        {
                            "path": "/ip",
                            "method": "GET",
                            "match_pattern": "/ip",
                            "rewrite_to": "/headers",
                            "triggers": []
                        }
                    ]
                },
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/bc9cf71f3a234f116acfdf05f1ce6c5c/",
        "target_url": "http://httpbin.org/",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false,
        "cache_control_ttl_header": ""
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [
        {
            "name": "header_injector",
            "options": {}
        }
    ],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false,
    "config_data": {},
    "tag_headers": [],
    "global_rate_limit": {
        "rate": 0,
        "per": 0
    },
    "strip_auth_data": false
}
```

@excieve @buger also i noticed one thing, on cloud if we enable modify headers plugin and enable add/remove response headers that doesn't work. This plugin working fine on Hybrid and on-prem installations.

**Comment by ilijabojanovic** [comment]
Also here is work around for this issue:

```
{
    "id": "5a9ebd1555c18f000183f004",
    "name": "ilija9",
    "slug": "ilija9",
    "api_id": "bc9cf71f3a234f116acfdf05f1ce6c5c",
    "org_id": "5935d76307f81b0001c7c1a0",
    "use_keyless": true,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "",
        "use_certificate": false
    },
    "use_basic_auth": false,
    "use_mutual_tls_auth": false,
    "client_certificates": [],
    "upstream_certificates": {},
    "enable_jwt": false,
    "use_standard_auth": false,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "default_version": "",
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {
                    "transform_headers": [
                        {
                            "delete_headers": [
                                "postman-token",
                                "User-Agent"
                            ],
                            "add_headers": {
                                "ADD": "request"
                            },
                            "path": "/headers",
                            "method": "GET",
                            "act_on": false
                        },
                        {
                            "delete_headers": [
                                "User-Agent"
                            ],
                            "add_headers": {
                                "add": "request"
                            },
                            "path": "/ip",
                            "method": "GET",
                            "act_on": false
                        }
                    ],
                    "transform_response_headers": [
                        {
                            "delete_headers": [
                                "X-Powered-By"
                            ],
                            "add_headers": {
                                "add": "response"
                            },
                            "path": "/headers",
                            "method": "GET",
                            "act_on": false
                        },
                        {
                            "delete_headers": [
                                "X-Powered-By"
                            ],
                            "add_headers": {
                                "add": "response"
                            },
                            "path": "/ip",
                            "method": "GET",
                            "act_on": false
                        }
                    ],
                    "url_rewrites": [
                        {
                            "path": "/ip",
                            "method": "GET",
                            "match_pattern": "/ip",
                            "rewrite_to": "/headers",
                            "triggers": []
                        }
                    ]
                },
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/bc9cf71f3a234f116acfdf05f1ce6c5c/",
        "target_url": "http://httpbin.org/",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "",
            "port_data_path": "",
            "target_path": "",
            "use_target_list": false,
            "cache_timeout": 0,
            "endpoint_returns_list": false
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false,
        "cache_control_ttl_header": ""
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [
        {
            "name": "header_injector",
            "options": {}
        }
    ],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false,
    "config_data": {},
    "tag_headers": [],
    "global_rate_limit": {
        "rate": 0,
        "per": 0
    },
    "strip_auth_data": false
}
```
If we enable modify headers on endpoint which is same in rewrite url, gateway returns response headers

**Comment by ilijabojanovic** [comment]
Verified and fixed in:
https://github.com/TykTechnologies/tyk/pull/1515

**Comment by letzya** [comment]
Sorry, but don't think it's  working.
1. create api
2. add endpoint and tick modify header.
3. set 'ip'  as the endpoint add header on the **response**(x-tyk-new 123)
4. Confirm you can see the header
5. Add url rewrite(http://httpbin.org/xml for instance)
6. Test and see that header dissapears
(I think it hasn't disappeared  on the first try)

**Comment by LuanvP** [comment]
@letzya 
I just tested on-prem master and it's working for me:
- Tried naming endpoint ip and /ip and rewriting to xml and http://httpbin.org/xml
- In all cases I could still see the added header in response -  tyk-test: 123

**Comment by letzya** [comment]
Ok, will check. Maybe my env was not up to date with the fix.

**Comment by ilijabojanovic** [comment]
@LuanvP @letzya i we just check again master, all working fine for me on endpoints with/without backslash

**Comment by ilijabojanovic** [comment]
@letzya any update?
