### ISSUE TITLE
Please include a nested JSON object on the policy

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk#2717]
Regarding https://support.tyk.io/a/tickets/3793,

Could we please request an enhancement to include a nested JSON object, similar to this one, on the policy(https://tyk.io/docs/security/security-policies/policies-guide/) ? Can this also be prioritised to be bundled with the 2.8.3 please ? 

We just want a nested JSON object, similar to this one, included on the Oauth client & on the policy definition.

  "meta_data" :{      "key1": "value1",      "key2": "value2",      "key3": "value3"}

**Comment by jensneuse** [comment]
What problem are we solving?

**Comment by christtyk** [comment]
@jensneuse have given @furkansenharputlu details of the support ticket, if you'd like it let me know

**Comment by ilijabojanovic** [comment]
@furkansenharputlu 

Seems we have some merge issue on something. Metadata filed are visible on policy page, when we update policy with metadata api returns 200 status code, but data is not saved in database.

<img width="1659" alt="Screen Shot 2019-12-30 at 21 32 04" src="https://user-images.githubusercontent.com/8557292/71599859-eb18c780-2b4c-11ea-9fa3-a5a0218f2ea2.png">

<img width="1664" alt="Screen Shot 2019-12-30 at 21 32 11" src="https://user-images.githubusercontent.com/8557292/71599866-f53ac600-2b4c-11ea-96bb-195745c1ac6d.png">

But data isn't saved in Database 

<img width="1268" alt="Screen Shot 2019-12-30 at 21 40 49" src="https://user-images.githubusercontent.com/8557292/71599909-1996a280-2b4d-11ea-9717-b4bc5094831b.png">

**Comment by furkansenharputlu** [comment]
@ilijabojanovic the dashboard change wasn't added to the release branch. I added, It should work now.

**Comment by ilijabojanovic** [comment]
@furkansenharputlu on latest release-1.9 branch i still don't see this change
https://github.com/TykTechnologies/tyk-analytics/commits/release-1.9

**Comment by furkansenharputlu** [comment]
@ilijabojanovic @maciejwojciechowski this is the change https://github.com/TykTechnologies/tyk-analytics/commit/d1d7e4bb672e2e15c01e235e7ab70980ed9e372a

**Comment by maciejwojciechowski** [comment]
meta is not visible on UI when opening policy. seems UI issue as data is present in response

![image](https://user-images.githubusercontent.com/39672152/71822654-ac779580-3095-11ea-8981-70a2b0bb8f8c.png)

**Comment by christtyk** [comment]
@furkansenharputlu if there's any risk this won't be included please let me know, is for a large client.

**Comment by furkansenharputlu** [comment]
@christtyk it will be released. @lghiur, the comment above that @maciejwojciechowski added shows that it seems a FE issue. Can you please have a look ?

**Comment by maciejwojciechowski** [comment]
verified
